#!/usr/bin/python
"""
Define basic parameter IDs for objects
"""
objects = {
        'mileticova_60_1vl': {
        'host': '10.4.1.150',
        'slot': '2',
        'pon': 'pon.10',
        'profileID': '3',
        'pppoeID': '23',
        'mgmtID': '24',
        'igmpID': '25',
        'mcastID': '13',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'2',
    },

        'mileticova_60_2vl': {
        'host': '10.4.1.150',
        'slot': '2',
        'pon': 'pon.11',
        'profileID': '3',
        'pppoeID': '23',
        'mgmtID': '24',
        'igmpID': '25',
        'mcastID': '13',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'2',
    },

        'primyte_1etapa_1vl': {
        'host': '192.168.82.19',
        'slot': '1',
        'pon': 'pon.1',
        'profileID': '3',
        'pppoeID': '3',
        'mgmtID': '4',
        'igmpID': '2',
        'mcastID': '1',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'slnecnice_3etapa_B1_B2': {
        'host': '192.168.35.51',
        'slot': '1',
        'pon': 'pon.1',
        'profileID': '3',
        'pppoeID': '4',
        'mgmtID': '1',
        'igmpID': '2',
        'mcastID': '3',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'shc3_olt_pon8': {
        'host': '192.168.35.51',
        'slot': '1',
        'pon': 'pon.8',
        'profileID': '4',
        'pppoeID': '4',
        'mgmtID': '1',
        'igmpID': '2',
        'mcastID': '3',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'slnecnice_3etapa_B3_B4': {
        'host': '192.168.35.51',
        'slot': '1',
        'pon': 'pon.2',
        'profileID': '3',
        'pppoeID': '4',
        'mgmtID': '1',
        'igmpID': '2',
        'mcastID': '3',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'slnecnice_3etapa_B5_B6': {
        'host': '192.168.35.51',
        'slot': '1',
        'pon': 'pon.3',
        'profileID': '3',
        'pppoeID': '4',
        'mgmtID': '1',
        'igmpID': '2',
        'mcastID': '3',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'slnecnice_3etapa_C1_C2': {
        'host': '192.168.35.51',
        'slot': '1',
        'pon': 'pon.4',
        'profileID': '3',
        'pppoeID': '4',
        'mgmtID': '1',
        'igmpID': '2',
        'mcastID': '3',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'dominant': {
        'host': '192.168.35.50',
        'slot': '1',
        'pon': 'pon.7',
        'profileID': '4',
        'pppoeID': '7',
        'mgmtID': '1',
        'igmpID': '5',
        'mcastID': '6',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'6',
        'mcastPKG':'1',
    },

        'jegeho_dole': { 
        'host': '10.4.1.150',
        'slot': '3',
        'pon': 'pon.7',
        'profileID': '3',
        'pppoeID': '2',
        'mgmtID': '5',
        'igmpID': '3',
        'mcastID': '1',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    },

        'jegeho_hore': { 
        'host': '10.4.1.150',
        'slot': '3',
        'pon': 'pon.8',
        'profileID': '3',
        'pppoeID': '2',
        'mgmtID': '5',
        'igmpID': '3',
        'mcastID': '1',
        'mgmtUP':'1',
        'igmpUP':'1',
        'pppoeUP':'4',
        'mcastPKG':'1',
    }
}
